### ISSUE TITLE
FYI - text2vec

### ISSUE THREAD

**Issue by dselivanov** [mlampros/GloveR#1]
Hi, during exploration of new github tags functionality found this repo (by clicking to glove tag). Just to let you  know - here is faster and more accurate implementation of GloVe - https://github.com/dselivanov/text2vec.
Also discovered you fastTextR package. Would be great to join forces and create more functional wrapper with R interface (not just working with files).

**Comment by mlampros** [comment]
hello and I'm sorry for the late reply, 
I'am aware of the text2vec package (I already used it in the past) and thanks for sharing. Now, to both GloveR and fastTextR my main intention was to create R wrappers from existing C/C++ code and not to implement the algorithms as you have done in your text2vec package for GloVe. I agree that the fastText algorithm deserves a better R interface similar to the  [python package](https://github.com/salestock/fastText.py), but you should know that I've started learning C++ 10 months ago and the fastTextR wrapper was carefully done so that only parts can be included that do not cause any issues.
